version: "3.8"

services:
  ## Spark Master Service
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8080:8080"    # Spark Master Web UI
      - "7077:7077"    # Spark Master Port

  ## Spark Worker 1 Service
  spark-worker1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    depends_on:
      - spark-master

  ## Spark Worker 2 Service
  spark-worker2:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    depends_on:
      - spark-master

  ## Jupyter Notebook Service
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    environment:
      # Ensure the notebook knows where the Spark master is located.
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master

  ## MinIO Service
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # MinIO API port
      - "9090:9090" # MinIO Console port
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /minio-image/storage --console-address :9090
    volumes:
      - minio-data:/data

volumes:
  minio-data:
